### ISSUE TITLE
Runtime Error in https://huggingface.co/spaces/vuu10/EnzRank

### ISSUE THREAD

**Issue by Cr737** [maranasgroup/EnzRank#1]
Runtime error
Traceback (most recent call last):
  File "/home/user/.local/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/user/.local/lib/python3.8/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/user/.local/lib/python3.8/site-packages/streamlit/delta_generator.py", line 45, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "/home/user/.local/lib/python3.8/site-packages/streamlit/elements/arrow_altair.py", line 35, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'
Container logs:

===== Application Startup at 2023-07-31 10:01:34 =====

Traceback (most recent call last):
  File "/home/user/.local/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/user/.local/lib/python3.8/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/user/.local/lib/python3.8/site-packages/streamlit/delta_generator.py", line 45, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "/home/user/.local/lib/python3.8/site-packages/streamlit/elements/arrow_altair.py", line 35, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'
![image](https://github.com/maranasgroup/EnzRank/assets/101084177/94cf522c-df21-4066-9aaf-e4d128725244)

**Comment by Cr737** [comment]
It happened when I connected https://huggingface.co/spaces/vuu10/EnzRank

**Comment by Vik-u** [comment]
Hi, It was an error with the hugging face and streamlit version updates. I have made the changes and huggingface interface works now. Please let me know if you still have the same issue. Thanks

**Comment by Cr737** [comment]
It works, thanks
